{% set data = load_setuptools() %}

package:
  name: nwb-extensions-smithy
  version: {{ (data.get('version') or '0.1.0dev2') | replace('+', '_') | replace('/', '_') | replace('-', '_')}}

source:
  path: ../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - feedstocks = nwb_extensions_smithy.feedstocks:main
    - nwb-extensions-smithy = nwb_extensions_smithy.cli:main

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda >=4.2
    - conda-build >=3.18.3
    - jinja2
    - requests
    - pycryptodome
    - gitpython
    - pygithub
    - ruamel.yaml
    - conda-forge-pinning
    - vsts-python-api
    - toolz

test:
  requires:
    - mock
    - pytest
  imports:
    - nwb_extensions_smithy
    - nwb_extensions_smithy.ci_register
    - nwb_extensions_smithy.configure_feedstock
  source_files:
    - tests
  commands:
    - nwb-extensions-smithy --help
    - py.test tests

about:
  home: https://github.com/nwb-extensions/nwb-extensions-smithy
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A package to create repositories for NWB extension recipes, and automate their building with CI tools on Linux, OSX and Windows.
